# Библиотека еды: скачивает модели Poly Haven (CC0), пережимает текстуры и упаковывает каждую в один GLB
# внутри box-studio-food/<id>.js; пишет список моделей с превью в src/app/core/food-library.js.
# Запуск (нужны Python 3 и Pillow): python3 tools/food_library.py
import base64, io, json, struct, urllib.request
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'box-studio-food'
FOOD = [  # id Poly Haven, название, сколько px у цвета / рельефа / ARM
  ('croissant', 'Круассан'), ('hamburger_buns', 'Булочки'), ('carrot_cake', 'Морковный торт'),
  ('strawberry_chocolate_cake', 'Шоколадный торт с клубникой'), ('food_apple_01', 'Яблоко'), ('lemon', 'Лимон'),
  ('food_kiwi_01', 'Киви'), ('food_avocado_01', 'Авокадо'), ('food_lime_01', 'Лайм'), ('food_pomegranate_01', 'Гранат'),
]
SIZES = {'diff': (1024, 82), 'nor': (1024, 88), 'arm': (512, 82)}   # max side px, JPEG quality

def get(url):
  req = urllib.request.Request(url, headers={'User-Agent': 'box-studio-3d food library'})
  with urllib.request.urlopen(req, timeout=60) as r: return r.read()

def jpeg(data, kind):
  side, q = SIZES[kind]
  im = Image.open(io.BytesIO(data)).convert('RGB')
  if max(im.size) > side: im.thumbnail((side, side), Image.LANCZOS)
  b = io.BytesIO(); im.save(b, 'JPEG', quality=q, optimize=True, progressive=False); return b.getvalue()

def kind_of(name):
  return 'nor' if 'nor' in name else 'arm' if ('arm' in name or 'rough' in name) else 'diff'

def pack(asset_id):
  base = f'https://dl.polyhaven.org/file/ph-assets/Models/gltf/1k/{asset_id}/'
  files = json.loads(get(f'https://api.polyhaven.com/files/{asset_id}'))['gltf']['1k']['gltf']
  gltf = json.loads(get(files['url']))
  inc = files['include']
  bins = [get(inc[b['uri']]['url']) for b in gltf['buffers']]
  # one buffer: the original bins, then each picture
  blob, offs = bytearray(), []
  for b in bins: offs.append(len(blob)); blob += b; blob += b'\0' * (-len(blob) % 4)
  for v in gltf['bufferViews']: v['byteOffset'] = v.get('byteOffset', 0) + offs[v.get('buffer', 0)]; v['buffer'] = 0
  for im in gltf['images']:
    data = jpeg(get(inc[im['uri']]['url']), kind_of(im['uri']))
    gltf['bufferViews'].append({'buffer': 0, 'byteOffset': len(blob), 'byteLength': len(data)})
    im.pop('uri'); im['bufferView'] = len(gltf['bufferViews']) - 1; im['mimeType'] = 'image/jpeg'
    blob += data; blob += b'\0' * (-len(blob) % 4)
  gltf['buffers'] = [{'byteLength': len(blob)}]
  js = json.dumps(gltf, separators=(',', ':')).encode(); js += b' ' * (-len(js) % 4)
  glb = struct.pack('<III', 0x46546C67, 2, 12 + 8 + len(js) + 8 + len(blob)) + struct.pack('<II', len(js), 0x4E4F534A) + js + struct.pack('<II', len(blob), 0x004E4942) + bytes(blob)
  return glb

def thumb(asset_id):
  im = Image.open(io.BytesIO(get(f'https://cdn.polyhaven.com/asset_img/thumbs/{asset_id}.png?width=192&height=192'))).convert('RGBA')
  im.thumbnail((96, 96), Image.LANCZOS)
  bg = Image.new('RGB', im.size, (244, 241, 235)); bg.paste(im, mask=im.split()[3])
  b = io.BytesIO(); bg.save(b, 'JPEG', quality=80); return 'data:image/jpeg;base64,' + base64.b64encode(b.getvalue()).decode()

def main():
  OUT.mkdir(exist_ok=True)
  items = []
  for asset_id, name in FOOD:
    info = json.loads(get(f'https://api.polyhaven.com/info/{asset_id}'))
    glb = pack(asset_id)
    (OUT / f'{asset_id}.js').write_text(f"// {name} — Poly Haven «{info['name']}», CC0 (polyhaven.com/a/{asset_id}). Сгенерировано tools/food_library.py\n"
                                       f"window.__bsFood && window.__bsFood('{asset_id}', '{base64.b64encode(glb).decode()}');\n")
    dims = [round(v) for v in info.get('dimensions', [100, 100, 100])]
    items.append({'id': asset_id, 'name': name, 'size': max(dims), 'tris': info.get('polycount'), 'kb': round(len(glb) / 1024), 'thumb': thumb(asset_id)})
    print(asset_id, len(glb) // 1024, 'КБ')
  body = ',\n'.join('  ' + json.dumps(it, ensure_ascii=False) for it in items)
  (ROOT / 'src/app/core/food-library.js').write_text(
    '// Библиотека еды: готовые лёгкие модели (Poly Haven, CC0) — список с превью; сами модели в box-studio-food/, грузятся по клику\n'
    '/* Generated by tools/food_library.py: id, name, size (longest side, mm), tris, kb (the GLB), thumb (a small picture). */\n'
    f'const FOOD = [\n{body},\n];\n\nexport {{ FOOD }};\n')

main()
